### PR TITLE
Add beverages menu

### PR DESCRIPTION
**Pull request by HelloYeew**
Add beverages menu and add a link on README file

### CODE REVIEW

**Comment by patkamon** [comment]
+1 
good, Everything looks excellent.

**Review by peach007 — COMMENTED** [review]
Good job

**Comment by pattanan-cyber** [comment]
Good.You are really improving

**Comment by vnsvakanda** [comment]
Nice work!

**Comment by HelloYeew** [comment]
Thanks for review! Merging.

**Pull request merged**
